# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18984c5837f4adcf176e45bc6f5e4fc27c027737e42fd94dafa51718f73ff4f2dfc723986da4ae6e4774d64406462bfaa3504d99dd0577aba163d88f5978e7e6

test:
  secret_key_base: b198ef183bc29bcae340b4ac2f6b9bb50662163b5925a8d82d487be5e3465a1fbc31a2bbafff551b81ffb9c2b5cdcbe7a1447f62532b8fd93a8e1aeb903671f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
